package com.synfusion.pipelistpro.utils

import android.content.Context
import android.content.Intent
import androidx.core.content.FileProvider
import com.synfusion.pipelistpro.model.Project
import java.io.File

object ShareUtils {

    fun shareProjectAsText(context: Context, project: Project) {
        val text = StringBuilder()
        text.append("*${project.projectName} - Material List*\n")
        text.append("Client: ${project.clientName}\n")
        text.append("Location: ${project.location}\n")
        text.append("Date: ${project.date}\n\n")

        project.items.forEachIndexed { index, item ->
            text.append("${index + 1}. ${item.materialName} (${item.size}) — ${item.quantity} ${item.unit}\n")
            if (item.notes.isNotEmpty()) {
                text.append("   Note: ${item.notes}\n")
            }
        }

        val categoryGroups = project.items.groupBy { it.category }
        if (categoryGroups.isNotEmpty()) {
            text.append("\n*Summary*\n")
            text.append("Total Items: ${project.items.size}\n")
            categoryGroups.forEach { (category, items) ->
                text.append("$category: ${items.size}\n")
            }
        }

        text.append("\n_Generated by PipeList Pro_")

        val intent = Intent(Intent.ACTION_SEND)
        intent.type = "text/plain"
        intent.putExtra(Intent.EXTRA_TEXT, text.toString())
        context.startActivity(Intent.createChooser(intent, "Share via"))
    }

    fun sharePdfFile(context: Context, file: File) {
        val uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.fileprovider",
            file
        )
        val intent = Intent(Intent.ACTION_SEND)
        intent.type = "application/pdf"
        intent.putExtra(Intent.EXTRA_STREAM, uri)
        intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        context.startActivity(Intent.createChooser(intent, "Share PDF via"))
    }
}
