package com.synfusion.pipelistpro.pdf

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import com.synfusion.pipelistpro.model.Project
import java.io.File
import java.io.FileOutputStream

object PdfGenerator {

    private const val PAGE_WIDTH = 595
    private const val PAGE_HEIGHT = 842
    private const val MARGIN = 40f
    private const val CONTENT_BOTTOM_LIMIT = 780f

    fun generateProjectPdf(context: Context, project: Project): File? {
        val pdfDocument = PdfDocument()
        val paint = Paint()

        var pageCount = 1
        var page = startNewPage(pdfDocument, pageCount)
        var canvas = page.canvas

        drawHeader(canvas, project, paint)

        var y = 130f // Start after header

        // Group items by category
        val groupedItems = project.items.groupBy { it.category }

        var index = 1

        groupedItems.forEach { (category, items) ->
            // Draw Category Header
            if (y + 40f > CONTENT_BOTTOM_LIMIT) {
                drawFooter(canvas, paint)
                pdfDocument.finishPage(page)
                pageCount++
                page = startNewPage(pdfDocument, pageCount)
                canvas = page.canvas
                y = MARGIN + 20f
            }

            y += 10f
            paint.textSize = 16f
            paint.isFakeBoldText = true
            paint.color = Color.BLACK
            canvas.drawText("$category Material List", MARGIN, y, paint)
            y += 25f

            items.forEach { item ->
                // Check if we need a new page for item
                val requiredHeight = if (item.notes.isNotEmpty()) 35f else 20f
                if (y + requiredHeight > CONTENT_BOTTOM_LIMIT) {
                    drawFooter(canvas, paint)
                    pdfDocument.finishPage(page)
                    pageCount++
                    page = startNewPage(pdfDocument, pageCount)
                    canvas = page.canvas
                    y = MARGIN + 20f
                }

                drawItemRow(canvas, item, index, y, paint)
                index++
                y += 25f
            }

            // Add a little space after each category
            y += 15f
        }

        drawFooter(canvas, paint)
        pdfDocument.finishPage(page)

        val file = File(context.cacheDir, "${project.projectName.replace(" ", "_")}_List.pdf")
        return try {
            val outputStream = FileOutputStream(file)
            pdfDocument.writeTo(outputStream)
            outputStream.close()
            pdfDocument.close()
            file
        } catch (e: Exception) {
            e.printStackTrace()
            pdfDocument.close()
            null
        }
    }

    private fun startNewPage(pdfDocument: PdfDocument, pageNumber: Int): PdfDocument.Page {
        val pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create()
        return pdfDocument.startPage(pageInfo)
    }

    private fun drawHeader(canvas: Canvas, project: Project, paint: Paint) {
        var y = 60f
        paint.textSize = 22f
        paint.isFakeBoldText = true
        paint.color = Color.BLACK
        canvas.drawText(project.projectName, MARGIN, y, paint)

        y += 25f
        paint.textSize = 14f
        paint.isFakeBoldText = false
        canvas.drawText("Date: ${project.date}", MARGIN, y, paint)

        y += 20f
        paint.strokeWidth = 1f
        paint.color = Color.LTGRAY
        canvas.drawLine(MARGIN, y, PAGE_WIDTH - MARGIN, y, paint)
    }

    private fun drawItemRow(canvas: Canvas, item: com.synfusion.pipelistpro.model.ProjectItem, index: Int, y: Float, paint: Paint) {
        paint.isFakeBoldText = false
        paint.textSize = 14f
        paint.color = Color.BLACK

        // Format: 1. 1" UPVC Ball Valve — 2 pcs
        val sizePrefix = if (item.size != "Standard" && item.size.isNotEmpty()) "${item.size} " else ""
        val itemText = "$index. $sizePrefix${item.materialName} — ${item.quantity} ${item.unit}"
        canvas.drawText(itemText, MARGIN, y, paint)
    }

    private fun drawFooter(canvas: Canvas, paint: Paint) {
        val footerText = "Generated by PipeList Pro"
        paint.textSize = 10f
        paint.isFakeBoldText = false
        paint.color = Color.LTGRAY
        paint.textAlign = Paint.Align.CENTER

        // Draw centered at the bottom
        canvas.drawText(footerText, PAGE_WIDTH / 2f, PAGE_HEIGHT - 30f, paint)

        // Reset alignment for other drawing operations
        paint.textAlign = Paint.Align.LEFT
    }
}
