package com.synfusion.pipelistpro.pdf

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import com.synfusion.pipelistpro.model.Project
import java.io.File
import java.io.FileOutputStream

object PdfGenerator {

    private const val PAGE_WIDTH = 595
    private const val PAGE_HEIGHT = 842
    private const val MARGIN = 40f
    private const val CONTENT_BOTTOM_LIMIT = 780f

    fun generateProjectPdf(context: Context, project: Project): File? {
        val pdfDocument = PdfDocument()
        val paint = Paint()

        var pageCount = 1
        var page = startNewPage(pdfDocument, pageCount)
        var canvas = page.canvas

        drawHeader(canvas, project, paint)

        var y = 175f // Start after header

        drawTableHeader(canvas, y, paint)
        y += 25f

        project.items.forEach { item ->
            // Check if we need a new page
            val requiredHeight = if (item.notes.isNotEmpty()) 35f else 20f
            if (y + requiredHeight > CONTENT_BOTTOM_LIMIT) {
                pdfDocument.finishPage(page)
                pageCount++
                page = startNewPage(pdfDocument, pageCount)
                canvas = page.canvas
                y = MARGIN + 20f
                drawTableHeader(canvas, y, paint)
                y += 25f
            }

            drawItemRow(canvas, item, y, paint)
            y += 20f

            if (item.notes.isNotEmpty()) {
                paint.textSize = 10f
                paint.color = Color.GRAY
                canvas.drawText("Note: ${item.notes}", MARGIN + 10f, y, paint)
                y += 15f
                paint.textSize = 14f
                paint.color = Color.BLACK
            }
        }

        drawFooter(canvas, paint)
        pdfDocument.finishPage(page)

        val file = File(context.cacheDir, "${project.projectName.replace(" ", "_")}_List.pdf")
        return try {
            val outputStream = FileOutputStream(file)
            pdfDocument.writeTo(outputStream)
            outputStream.close()
            pdfDocument.close()
            file
        } catch (e: Exception) {
            e.printStackTrace()
            pdfDocument.close()
            null
        }
    }

    private fun startNewPage(pdfDocument: PdfDocument, pageNumber: Int): PdfDocument.Page {
        val pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create()
        return pdfDocument.startPage(pageInfo)
    }

    private fun drawHeader(canvas: Canvas, project: Project, paint: Paint) {
        var y = 50f
        paint.textSize = 24f
        paint.isFakeBoldText = true
        paint.color = Color.parseColor("#004AAD")
        canvas.drawText("PipeList Pro", MARGIN, y, paint)

        y += 40f
        paint.textSize = 18f
        paint.color = Color.BLACK
        canvas.drawText("Material List: ${project.projectName}", MARGIN, y, paint)

        y += 25f
        paint.textSize = 14f
        paint.isFakeBoldText = false
        canvas.drawText("Client: ${project.clientName}", MARGIN, y, paint)

        y += 20f
        canvas.drawText("Location: ${project.location}", MARGIN, y, paint)

        y += 20f
        canvas.drawText("Date: ${project.date}", MARGIN, y, paint)

        y += 20f
        paint.strokeWidth = 2f
        canvas.drawLine(MARGIN, y, PAGE_WIDTH - MARGIN, y, paint)
    }

    private fun drawTableHeader(canvas: Canvas, y: Float, paint: Paint) {
        paint.textSize = 14f
        paint.isFakeBoldText = true
        paint.color = Color.BLACK
        canvas.drawText("Item Name", MARGIN, y, paint)
        canvas.drawText("Size", 300f, y, paint)
        canvas.drawText("Qty", 450f, y, paint)
        canvas.drawText("Unit", 500f, y, paint)

        val lineY = y + 5f
        paint.strokeWidth = 1f
        canvas.drawLine(MARGIN, lineY, PAGE_WIDTH - MARGIN, lineY, paint)
    }

    private fun drawItemRow(canvas: Canvas, item: com.synfusion.pipelistpro.model.ProjectItem, y: Float, paint: Paint) {
        paint.isFakeBoldText = false
        paint.textSize = 12f
        canvas.drawText(item.materialName, MARGIN, y, paint)
        canvas.drawText(item.size, 300f, y, paint)
        canvas.drawText(item.quantity.toString(), 450f, y, paint)
        canvas.drawText(item.unit, 500f, y, paint)
    }

    private fun drawFooter(canvas: Canvas, paint: Paint) {
        paint.textSize = 10f
        paint.isFakeBoldText = false
        paint.color = Color.LTGRAY
        canvas.drawText("Generated by PipeList Pro", MARGIN, PAGE_HEIGHT - 30f, paint)
    }
}
