package com.synfusion.pipelistpro.pdf

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import com.synfusion.pipelistpro.model.Project
import java.io.File
import java.io.FileOutputStream

object PdfGenerator {

    fun generateProjectPdf(context: Context, project: Project): File? {
        val pdfDocument = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4 Size
        val page = pdfDocument.startPage(pageInfo)
        val canvas: Canvas = page.canvas
        val paint = Paint()

        var y = 40f

        // Header
        paint.textSize = 24f
        paint.isFakeBoldText = true
        paint.color = Color.parseColor("#004AAD")
        canvas.drawText("PipeList Pro", 40f, y, paint)

        y += 40f
        paint.textSize = 18f
        paint.color = Color.BLACK
        canvas.drawText("Material List: ${project.projectName}", 40f, y, paint)

        y += 25f
        paint.textSize = 14f
        paint.isFakeBoldText = false
        canvas.drawText("Client: ${project.clientName}", 40f, y, paint)

        y += 20f
        canvas.drawText("Location: ${project.location}", 40f, y, paint)

        y += 20f
        canvas.drawText("Date: ${project.date}", 40f, y, paint)

        y += 30f
        paint.strokeWidth = 2f
        canvas.drawLine(40f, y, 555f, y, paint)

        // Table Header
        y += 30f
        paint.isFakeBoldText = true
        canvas.drawText("Item Name", 40f, y, paint)
        canvas.drawText("Size", 300f, y, paint)
        canvas.drawText("Qty", 450f, y, paint)
        canvas.drawText("Unit", 500f, y, paint)

        y += 15f
        paint.isFakeBoldText = false
        paint.strokeWidth = 1f
        canvas.drawLine(40f, y, 555f, y, paint)

        // Table Rows
        y += 25f
        project.items.forEach { item ->
            if (y > 780) { // Simple page break check (could be improved)
                pdfDocument.finishPage(page)
                // In a real app we'd start a new page here, for now keeping it single page for lightness
                return@forEach
            }

            canvas.drawText(item.materialName, 40f, y, paint)
            canvas.drawText(item.size, 300f, y, paint)
            canvas.drawText(item.quantity.toString(), 450f, y, paint)
            canvas.drawText(item.unit, 500f, y, paint)

            y += 20f
            if (item.notes.isNotEmpty()) {
                paint.textSize = 10f
                paint.color = Color.GRAY
                canvas.drawText("Note: ${item.notes}", 50f, y, paint)
                y += 15f
                paint.textSize = 14f
                paint.color = Color.BLACK
            }
        }

        // Footer
        paint.textSize = 12f
        paint.color = Color.LTGRAY
        canvas.drawText("Generated by PipeList Pro", 40f, 810f, paint)

        pdfDocument.finishPage(page)

        val file = File(context.cacheDir, "${project.projectName.replace(" ", "_")}_List.pdf")
        return try {
            pdfDocument.writeTo(FileOutputStream(file))
            pdfDocument.close()
            file
        } catch (e: Exception) {
            e.printStackTrace()
            pdfDocument.close()
            null
        }
    }
}
