package com.synfusion.pipelistpro.core.export

import android.content.Context
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import com.synfusion.pipelistpro.data.models.Project
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileOutputStream

object ImageExportManager {

    private const val WIDTH = 1080
    private const val MARGIN = 60f
    private const val MAX_HEIGHT = 8000 // To prevent OOM

    suspend fun generateImage(context: Context, project: Project): File? = withContext(Dispatchers.IO) {
        val paint = Paint(Paint.ANTI_ALIAS_FLAG)
        val groupedItems = project.items.groupBy { it.category }

        // Calculate dynamic height
        var totalHeight = 300f // Header
        groupedItems.forEach { (_, items) ->
            totalHeight += 80f // Category header
            totalHeight += items.size * 60f // Rows
            totalHeight += 40f // Spacing
        }
        totalHeight += 100f // Footer

        val finalHeight = totalHeight.toInt().coerceAtMost(MAX_HEIGHT)

        try {
            val bitmap = Bitmap.createBitmap(WIDTH, finalHeight, Bitmap.Config.ARGB_8888)
            val canvas = Canvas(bitmap)
            canvas.drawColor(Color.WHITE)

            var y = 100f

            // Header
            paint.textSize = 48f
            paint.isFakeBoldText = true
            paint.color = Color.BLACK
            canvas.drawText("PipeList Pro", MARGIN, y, paint)

            y += 60f
            paint.textSize = 28f
            paint.isFakeBoldText = false
            paint.color = Color.DKGRAY
            canvas.drawText(project.projectName, MARGIN, y, paint)

            y += 40f
            paint.textSize = 20f
            canvas.drawText("Date: ${project.date}", MARGIN, y, paint)

            y += 30f
            paint.strokeWidth = 3f
            paint.color = Color.BLACK
            canvas.drawLine(MARGIN, y, WIDTH - MARGIN, y, paint)

            y += 80f

            // Content
            groupedItems.forEach { (category, items) ->
                if (y > finalHeight - 150f) return@forEach // Prevent drawing out of bounds

                paint.textSize = 32f
                paint.isFakeBoldText = true
                paint.color = Color.rgb(0, 87, 217) // Primary Blue
                canvas.drawText(category.uppercase(), MARGIN, y, paint)

                y += 15f
                paint.strokeWidth = 2f
                paint.color = Color.LTGRAY
                canvas.drawLine(MARGIN, y, WIDTH - MARGIN, y, paint)
                y += 60f

                items.forEachIndexed { index, item ->
                    if (y > finalHeight - 100f) return@forEachIndexed

                    paint.textSize = 26f
                    paint.isFakeBoldText = false
                    paint.color = Color.BLACK

                    val sizeStr = if (item.size != "Standard" && item.size.isNotEmpty()) "${item.size} " else ""
                    val ftStr = if (item.ft != null) " (${item.ft} ft) " else ""
                    val itemText = "${index + 1}. $sizeStr${item.name}$ftStr"
                    val qtyText = "${item.quantity} ${item.unit}"

                    canvas.drawText(itemText, MARGIN + 20f, y, paint)

                    paint.textAlign = Paint.Align.RIGHT
                    canvas.drawText(qtyText, WIDTH - MARGIN, y, paint)
                    paint.textAlign = Paint.Align.LEFT

                    y += 60f
                }
                y += 20f
            }

            // Footer
            y = finalHeight - 50f
            paint.textSize = 20f
            paint.color = Color.GRAY
            paint.textAlign = Paint.Align.CENTER
            canvas.drawText("Generated by PipeList Pro", WIDTH / 2f, y, paint)

            val exportDir = File(context.cacheDir, "exports")
            if (!exportDir.exists()) exportDir.mkdirs()

            val fileName = "PipeList_${project.projectName.replace(" ", "_")}_${System.currentTimeMillis()}.png"
            val file = File(exportDir, fileName)

            val out = FileOutputStream(file)
            bitmap.compress(Bitmap.CompressFormat.PNG, 100, out)
            out.flush()
            out.close()

            file
        } catch (e: Exception) {
            e.printStackTrace()
            null
        }
    }
}
