package com.synfusion.pipelistpro.core.export

import android.content.Context
import android.content.Intent
import android.net.Uri
import androidx.core.content.FileProvider
import com.synfusion.pipelistpro.data.models.Project
import java.io.File
import java.util.Locale

object ShareManager {
    fun shareFile(context: Context, file: File, mimeType: String, title: String) {
        val uri: Uri = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = mimeType
            putExtra(Intent.EXTRA_STREAM, uri)
            clipData = android.content.ClipData.newUri(context.contentResolver, title, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(intent, title).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION))
    }

    fun shareText(context: Context, project: Project) {
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_TEXT, buildShareText(project))
        }
        context.startActivity(Intent.createChooser(intent, "Share material list"))
    }

    fun buildShareText(project: Project): String = buildString {
        appendLine("*PipeList Pro*")
        appendLine(project.projectName.ifBlank { "Material List" })
        appendLine("Date: ${project.date.ifBlank { "Not set" }}")
        if (project.notes.isNotBlank()) appendLine("Notes: ${project.notes}")
        appendLine()
        project.items.groupBy { it.category.ifBlank { "Other" } }.toSortedMap().forEach { (category, items) ->
            appendLine("*${category.uppercase(Locale.getDefault())}*")
            items.forEachIndexed { index, item ->
                val size = item.size.takeIf { it.isNotBlank() && it != "Standard" }?.let { "$it " }.orEmpty()
                val ft = item.ft?.let { " (${formatNumber(it)} ft)" }.orEmpty()
                appendLine("${index + 1}. $size${item.name}$ft - ${item.quantity} ${item.unit}")
            }
            appendLine()
        }
        appendLine("Generated by PipeList Pro")
    }

    private fun formatNumber(value: Double): String = if (value % 1.0 == 0.0) value.toInt().toString() else String.format(Locale.US, "%.2f", value).trimEnd('0').trimEnd('.')
}
